server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pjj_music?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&generateSimpleParameterMetadata=true
    username: root
    password: 20peng
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #springboot默认的是Hikari数据源   可以通过该属性修改默认数据源  这里使用的是阿里的Druid
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: org.pjj.music.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置日志
logging:
  level:
    root: info #全部日志级别为 info
    org.pjj.music: debug #该包下的日志级别为 debug
  file:
    name: log/music-log.log #将日志储存到 项目/log/music-log.log中